apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gibuserdb-secret
  namespace: edonusum
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: gibuserdb-secret
    creationPolicy: Owner
  data:
  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: gibuserdb