apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-git-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: infra-git-secret
    creationPolicy: Owner
    template:
      data:
        url: "https://github.com/ufuk-cetinkaya/infra.git"
        username: "ufuk-cetinkaya"
        password: "{{ .github_token_kv }}"
  data:
  - secretKey: github_token_kv
    remoteRef:
      key: github-token