apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store
  namespace: argocd
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://demo-aks-vault.vault.azure.net"
      tenantId: 226eefbc-6526-4679-82cb-27d07f52200c
      serviceAccountRef:
        name: workload-identity-sa